<div class="col-md-6"><label class="form-label">Nombre</label><input class="form-control" name="name" value="{{ old('name',$warehouse->name) }}" required></div>
<div class="col-md-3"><label class="form-label">Código</label><input class="form-control" name="code" value="{{ old('code',$warehouse->code) }}" required></div>
<div class="col-md-3"><label class="form-label">Tipo</label><select class="form-select" name="type">@foreach(['main'=>'Principal','branch'=>'Sucursal','pos'=>'POS','ecommerce'=>'Ecommerce'] as $k=>$v)<option value="{{ $k }}" @selected(old('type',$warehouse->type ?: 'branch')===$k)>{{ $v }}</option>@endforeach</select></div>
@foreach(['address'=>'Dirección','city'=>'Ciudad','commune'=>'Comuna','phone'=>'Teléfono','email'=>'Email'] as $field=>$label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><input class="form-control" name="{{ $field }}" value="{{ old($field,$warehouse->{$field}) }}"></div>@endforeach
<div class="col-md-6"><label class="form-label" for="region">Región</label><x-region-select :value="$warehouse->region" required /></div>
<div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked(old('is_active',$warehouse->exists ? $warehouse->is_active : true))><label class="form-check-label">Activa</label></div></div>
<div class="col-md-4"><label class="form-label">Prioridad de despacho</label><input class="form-control" type="number" min="1" max="9999" name="fulfillment_priority" value="{{ old('fulfillment_priority',$warehouse->fulfillment_priority ?: 100) }}" required></div>
<div class="col-md-8 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="is_central" value="1" @checked(old('is_central',$warehouse->is_central))><label class="form-check-label">Bodega central de respaldo (solo debe existir una)</label></div></div>
<div class="col-12 d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.warehouses.index') }}">Cancelar</a><button class="btn btn-primary">Guardar</button></div>
