@extends('layouts.admin')
@section('title','Calculadora de precios')
@section('page-title','Calculadora de precios')
@section('content')
<div class="row g-3"><div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-body"><form method="POST" action="{{ route('admin.pricing.calculator') }}" class="row g-3">@csrf
<div class="col-12"><label class="form-label">Producto</label><select class="form-select" name="product_id" required><option value="">Selecciona</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(request('product_id')==$product->id)>{{ $product->name }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label">Variante</label><select class="form-select" name="product_variant_id"><option value="">Sin variante</option>@foreach($variants as $variant)<option value="{{ $variant->id }}" @selected(request('product_variant_id')==$variant->id)>{{ $variant->product->name }} / {{ $variant->sku }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Cantidad</label><input class="form-control" name="quantity" type="number" min="1" value="{{ request('quantity',1) }}"></div><div class="col-md-6"><label class="form-label">Cupón</label><input class="form-control" name="coupon_code" value="{{ request('coupon_code') }}"></div>
<div class="col-12"><label class="form-label">Lista de precios</label><select class="form-select" name="price_list_id"><option value="">Default</option>@foreach($priceLists as $list)<option value="{{ $list->id }}" @selected(request('price_list_id')==$list->id)>{{ $list->name }}</option>@endforeach</select></div>
<div class="col-12"><button class="btn btn-primary w-100">Calcular</button></div></form></div></div></div>
<div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Resultado</div><div class="card-body">@if($result)<dl class="row"><dt class="col-sm-4">Precio base</dt><dd class="col-sm-8">${{ number_format($result['base_price'],0,',','.') }}</dd><dt class="col-sm-4">Precio oferta</dt><dd class="col-sm-8">{{ $result['sale_price'] ? '$'.number_format($result['sale_price'],0,',','.') : '-' }}</dd><dt class="col-sm-4">Precio final</dt><dd class="col-sm-8 fs-4 fw-bold">${{ number_format($result['final_price'],0,',','.') }}</dd></dl><h2 class="h6">Explicación</h2><ul>@foreach($result['trace'] as $line)<li>{{ $line }}</li>@endforeach</ul>@else<p class="text-secondary mb-0">Selecciona un producto para calcular el mejor precio disponible.</p>@endif</div></div></div></div>
@endsection
