<?php $__env->startSection('title', $title); ?>
<?php $__env->startSection('page-title', $title); ?>
<?php $__env->startSection('content'); ?>
    <div class="card border-0 shadow-sm">
        <div class="card-header bg-white d-flex justify-content-between"><span class="fw-semibold"><?php echo e($title); ?></span><a href="<?php echo e(route('admin.shipping.'.$route.'.create')); ?>" class="btn btn-dark btn-sm">Crear</a></div>
        <div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><?php $__currentLoopData = $columns; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><th><?php echo e($label); ?></th><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><th></th></tr></thead><tbody>
            <?php $__empty_1 = true; $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><?php $__currentLoopData = $columns; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><td><?php ($value = data_get($item, $key)); ?> <?php if($key === 'is_active'): ?><span class="badge <?php echo e($value ? 'text-bg-success' : 'text-bg-secondary'); ?>"><?php echo e($value ? 'Activo' : 'Inactivo'); ?></span><?php else: ?><?php echo e($value); ?><?php endif; ?></td><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?php echo e(route('admin.shipping.'.$route.'.edit', $item)); ?>">Editar</a><form class="d-inline" method="POST" action="<?php echo e(route('admin.shipping.'.$route.'.toggle', $item)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><button class="btn btn-sm btn-outline-warning">Estado</button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="<?php echo e(count($columns)+1); ?>" class="text-center text-secondary py-4">Sin registros.</td></tr><?php endif; ?>
        </tbody></table></div><div class="card-footer bg-white"><?php echo e($items->links()); ?></div>
    </div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Aplicaciones con c#\SitioWebQueeconomico\resources\views\admin\shipping\shared\index.blade.php ENDPATH**/ ?>