<?php $__env->startSection('title', 'Integraciones'); ?>
<?php $__env->startSection('content'); ?>
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h4">Integraciones</h1><a class="btn btn-primary" href="<?php echo e(route('admin.integrations.create')); ?>">Nueva integración</a></div>
<div class="row g-3 mb-3"><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted">Activas</div><div class="h3"><?php echo e($activeCount); ?></div></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted">Con error</div><div class="h3"><?php echo e($errorCount); ?></div></div></div></div></div>
<div class="card"><div class="card-body table-responsive"><table class="table align-middle"><thead><tr><th>Nombre</th><th>Tipo</th><th>Ambiente</th><th>Estado</th><th>Logs</th><th>Mapeos</th><th></th></tr></thead><tbody>
<?php $__currentLoopData = $integrations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $integration): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td><?php echo e($integration->name); ?><br><small class="text-muted"><?php echo e($integration->code); ?></small></td><td><?php echo e($integration->provider_type); ?></td><td><?php echo e($integration->environment); ?></td><td><?php echo e($integration->status); ?></td><td><?php echo e($integration->logs_count); ?></td><td><?php echo e($integration->product_mappings_count); ?></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?php echo e(route('admin.integrations.show', $integration)); ?>">Ver</a></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</tbody></table><?php echo e($integrations->links()); ?></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Aplicaciones con c#\SitioWebQueeconomico\resources\views\admin\integrations\index.blade.php ENDPATH**/ ?>