<?php $__env->startSection('title','Bodegas'); ?>
<?php $__env->startSection('page-title','Bodegas'); ?>
<?php $__env->startSection('content'); ?>
<div class="d-flex justify-content-between mb-3"><h1 class="h4">Bodegas</h1><a class="btn btn-primary" href="<?php echo e(route('admin.warehouses.create')); ?>">Crear bodega</a></div>
<form class="card border-0 shadow-sm mb-3"><div class="card-body"><div class="input-group"><input class="form-control" name="search" value="<?php echo e($search); ?>" placeholder="Buscar..."><button class="btn btn-outline-secondary">Buscar</button></div></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Nombre</th><th>Código</th><th>Tipo</th><th>Ciudad</th><th>Ubicaciones</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $warehouses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $warehouse): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($warehouse->name); ?></td><td><?php echo e($warehouse->code); ?></td><td><?php echo e($warehouse->type); ?></td><td><?php echo e($warehouse->city ?? '-'); ?></td><td><?php echo e($warehouse->locations_count); ?></td><td><span class="badge <?php echo e($warehouse->is_active ? 'text-bg-success':'text-bg-secondary'); ?>"><?php echo e($warehouse->is_active?'Activa':'Inactiva'); ?></span></td><td class="text-end"><div class="btn-group"><a class="btn btn-sm btn-outline-secondary" href="<?php echo e(route('admin.warehouses.show',$warehouse)); ?>">Ver</a><a class="btn btn-sm btn-outline-primary" href="<?php echo e(route('admin.warehouses.edit',$warehouse)); ?>">Editar</a><a class="btn btn-sm btn-outline-dark" href="<?php echo e(route('admin.warehouses.locations.index',$warehouse)); ?>">Ubicaciones</a></div></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center text-secondary py-4">Sin bodegas.</td></tr><?php endif; ?>
</tbody></table></div><?php if($warehouses->hasPages()): ?><div class="card-footer bg-white"><?php echo e($warehouses->links()); ?></div><?php endif; ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Aplicaciones con c#\SitioWebQueeconomico\resources\views\admin\warehouses\index.blade.php ENDPATH**/ ?>