<?php $__env->startSection('title',$config['title']); ?>
<?php $__env->startSection('page-title',$config['title']); ?>
<?php $__env->startSection('content'); ?>
<div class="d-flex justify-content-between mb-3"><h1 class="h4"><?php echo e($config['title']); ?></h1><a class="btn btn-primary" href="<?php echo e(route($config['routePrefix'].'.create')); ?>">Crear</a></div>
<form class="card border-0 shadow-sm mb-3"><div class="card-body"><div class="input-group"><input class="form-control" name="search" value="<?php echo e($search); ?>" placeholder="Buscar..."><button class="btn btn-outline-secondary">Buscar</button></div></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><?php $__currentLoopData = $config['columns']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><th><?php echo e($label); ?></th><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><th class="text-end">Acciones</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><?php $__currentLoopData = $config['columns']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><td><?php if(is_bool($item->{$key})): ?><?php echo e($item->{$key} ? 'Sí':'No'); ?><?php elseif($item->{$key} instanceof \Illuminate\Support\Carbon): ?><?php echo e($item->{$key}->format('d/m/Y H:i')); ?><?php else: ?><?php echo e($item->{$key} ?? '-'); ?><?php endif; ?></td><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><td class="text-end"><div class="btn-group"><a class="btn btn-sm btn-outline-secondary" href="<?php echo e(route($config['routePrefix'].'.show',$item)); ?>">Ver</a><a class="btn btn-sm btn-outline-primary" href="<?php echo e(route($config['routePrefix'].'.edit',$item)); ?>">Editar</a><?php if(in_array('is_active',$config['booleanFields'])): ?><form method="POST" action="<?php echo e(route($config['routePrefix'].'.toggle-active',$item)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><button class="btn btn-sm btn-outline-warning">Estado</button></form><?php endif; ?></div></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="<?php echo e(count($config['columns']) + 1); ?>" class="text-center text-secondary py-4">Sin registros.</td></tr><?php endif; ?>
</tbody></table></div><?php if($items->hasPages()): ?><div class="card-footer bg-white"><?php echo e($items->links()); ?></div><?php endif; ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Aplicaciones con c#\SitioWebQueeconomico\resources\views\admin\commercial\index.blade.php ENDPATH**/ ?>