<?php $__env->startSection('title','Calculadora de precios'); ?>
<?php $__env->startSection('page-title','Calculadora de precios'); ?>
<?php $__env->startSection('content'); ?>
<div class="row g-3"><div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-body"><form method="POST" action="<?php echo e(route('admin.pricing.calculator')); ?>" class="row g-3"><?php echo csrf_field(); ?>
<div class="col-12"><label class="form-label">Producto</label><select class="form-select" name="product_id" required><option value="">Selecciona</option><?php $__currentLoopData = $products; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $product): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($product->id); ?>" <?php if(request('product_id')==$product->id): echo 'selected'; endif; ?>><?php echo e($product->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
<div class="col-12"><label class="form-label">Variante</label><select class="form-select" name="product_variant_id"><option value="">Sin variante</option><?php $__currentLoopData = $variants; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $variant): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($variant->id); ?>" <?php if(request('product_variant_id')==$variant->id): echo 'selected'; endif; ?>><?php echo e($variant->product->name); ?> / <?php echo e($variant->sku); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
<div class="col-md-6"><label class="form-label">Cantidad</label><input class="form-control" name="quantity" type="number" min="1" value="<?php echo e(request('quantity',1)); ?>"></div><div class="col-md-6"><label class="form-label">Cupón</label><input class="form-control" name="coupon_code" value="<?php echo e(request('coupon_code')); ?>"></div>
<div class="col-12"><label class="form-label">Lista de precios</label><select class="form-select" name="price_list_id"><option value="">Default</option><?php $__currentLoopData = $priceLists; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $list): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($list->id); ?>" <?php if(request('price_list_id')==$list->id): echo 'selected'; endif; ?>><?php echo e($list->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
<div class="col-12"><button class="btn btn-primary w-100">Calcular</button></div></form></div></div></div>
<div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Resultado</div><div class="card-body"><?php if($result): ?><dl class="row"><dt class="col-sm-4">Precio base</dt><dd class="col-sm-8">$<?php echo e(number_format($result['base_price'],0,',','.')); ?></dd><dt class="col-sm-4">Precio oferta</dt><dd class="col-sm-8"><?php echo e($result['sale_price'] ? '$'.number_format($result['sale_price'],0,',','.') : '-'); ?></dd><dt class="col-sm-4">Precio final</dt><dd class="col-sm-8 fs-4 fw-bold">$<?php echo e(number_format($result['final_price'],0,',','.')); ?></dd></dl><h2 class="h6">Explicación</h2><ul><?php $__currentLoopData = $result['trace']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $line): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($line); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul><?php else: ?><p class="text-secondary mb-0">Selecciona un producto para calcular el mejor precio disponible.</p><?php endif; ?></div></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Aplicaciones con c#\SitioWebQueeconomico\resources\views\admin\pricing\calculator.blade.php ENDPATH**/ ?>